"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Plastics = exports.Physics = exports.Philosophy = exports.NuclearPower = exports.NuclearFission = exports.Navigation = exports.Mysticism = exports.Monarchy = exports.Metallurgy = exports.Medicine = exports.Mathematics = exports.MassProduction = exports.Masonry = exports.MapMaking = exports.Magnetism = exports.Literacy = exports.LaborUnion = exports.IronWorking = exports.Invention = exports.Industrialization = exports.HorsebackRiding = exports.Gunpowder = exports.GeneticEngineering = exports.FusionPower = exports.Flight = exports.Feudalism = exports.Explosives = exports.Engineering = exports.Electronics = exports.Electricity = exports.Democracy = exports.Currency = exports.Corporation = exports.Construction = exports.Conscription = exports.Computers = exports.Communism = exports.Combustion = exports.CodeOfLaws = exports.Chivalry = exports.Chemistry = exports.CeremonialBurial = exports.BronzeWorking = exports.BridgeBuilding = exports.Banking = exports.Automobile = exports.AtomicTheory = exports.Astronomy = exports.Alphabet = exports.AdvancedFlight = void 0;
exports.Writing = exports.University = exports.Trade = exports.TheoryOfGravity = exports.TheWheel = exports.TheRepublic = exports.Superconductor = exports.Steel = exports.SteamEngine = exports.SpaceFlight = exports.Rocketry = exports.Robotics = exports.Religion = exports.Refining = exports.Recycling = exports.Railroad = exports.Pottery = void 0;
var AdvancedFlight_1 = require("@civ-clone/base-science-advance-advancedflight/AdvancedFlight");
Object.defineProperty(exports, "AdvancedFlight", { enumerable: true, get: function () { return AdvancedFlight_1.AdvancedFlight; } });
var Alphabet_1 = require("@civ-clone/base-science-advance-alphabet/Alphabet");
Object.defineProperty(exports, "Alphabet", { enumerable: true, get: function () { return Alphabet_1.Alphabet; } });
var Astronomy_1 = require("@civ-clone/base-science-advance-astronomy/Astronomy");
Object.defineProperty(exports, "Astronomy", { enumerable: true, get: function () { return Astronomy_1.Astronomy; } });
var AtomicTheory_1 = require("@civ-clone/base-science-advance-atomictheory/AtomicTheory");
Object.defineProperty(exports, "AtomicTheory", { enumerable: true, get: function () { return AtomicTheory_1.AtomicTheory; } });
var Automobile_1 = require("@civ-clone/base-science-advance-automobile/Automobile");
Object.defineProperty(exports, "Automobile", { enumerable: true, get: function () { return Automobile_1.Automobile; } });
var Banking_1 = require("@civ-clone/base-science-advance-banking/Banking");
Object.defineProperty(exports, "Banking", { enumerable: true, get: function () { return Banking_1.Banking; } });
var BridgeBuilding_1 = require("@civ-clone/base-science-advance-bridgebuilding/BridgeBuilding");
Object.defineProperty(exports, "BridgeBuilding", { enumerable: true, get: function () { return BridgeBuilding_1.BridgeBuilding; } });
var BronzeWorking_1 = require("@civ-clone/base-science-advance-bronzeworking/BronzeWorking");
Object.defineProperty(exports, "BronzeWorking", { enumerable: true, get: function () { return BronzeWorking_1.BronzeWorking; } });
var CeremonialBurial_1 = require("@civ-clone/base-science-advance-ceremonialburial/CeremonialBurial");
Object.defineProperty(exports, "CeremonialBurial", { enumerable: true, get: function () { return CeremonialBurial_1.CeremonialBurial; } });
var Chemistry_1 = require("@civ-clone/base-science-advance-chemistry/Chemistry");
Object.defineProperty(exports, "Chemistry", { enumerable: true, get: function () { return Chemistry_1.Chemistry; } });
var Chivalry_1 = require("@civ-clone/base-science-advance-chivalry/Chivalry");
Object.defineProperty(exports, "Chivalry", { enumerable: true, get: function () { return Chivalry_1.Chivalry; } });
var CodeOfLaws_1 = require("@civ-clone/base-science-advance-codeoflaws/CodeOfLaws");
Object.defineProperty(exports, "CodeOfLaws", { enumerable: true, get: function () { return CodeOfLaws_1.CodeOfLaws; } });
var Combustion_1 = require("@civ-clone/base-science-advance-combustion/Combustion");
Object.defineProperty(exports, "Combustion", { enumerable: true, get: function () { return Combustion_1.Combustion; } });
var Communism_1 = require("@civ-clone/base-science-advance-communism/Communism");
Object.defineProperty(exports, "Communism", { enumerable: true, get: function () { return Communism_1.Communism; } });
var Computers_1 = require("@civ-clone/base-science-advance-computers/Computers");
Object.defineProperty(exports, "Computers", { enumerable: true, get: function () { return Computers_1.Computers; } });
var Conscription_1 = require("@civ-clone/base-science-advance-conscription/Conscription");
Object.defineProperty(exports, "Conscription", { enumerable: true, get: function () { return Conscription_1.Conscription; } });
var Construction_1 = require("@civ-clone/base-science-advance-construction/Construction");
Object.defineProperty(exports, "Construction", { enumerable: true, get: function () { return Construction_1.Construction; } });
var Corporation_1 = require("@civ-clone/base-science-advance-corporation/Corporation");
Object.defineProperty(exports, "Corporation", { enumerable: true, get: function () { return Corporation_1.Corporation; } });
var Currency_1 = require("@civ-clone/base-science-advance-currency/Currency");
Object.defineProperty(exports, "Currency", { enumerable: true, get: function () { return Currency_1.Currency; } });
var Democracy_1 = require("@civ-clone/base-science-advance-democracy/Democracy");
Object.defineProperty(exports, "Democracy", { enumerable: true, get: function () { return Democracy_1.Democracy; } });
var Electricity_1 = require("@civ-clone/base-science-advance-electricity/Electricity");
Object.defineProperty(exports, "Electricity", { enumerable: true, get: function () { return Electricity_1.Electricity; } });
var Electronics_1 = require("@civ-clone/base-science-advance-electronics/Electronics");
Object.defineProperty(exports, "Electronics", { enumerable: true, get: function () { return Electronics_1.Electronics; } });
var Engineering_1 = require("@civ-clone/base-science-advance-engineering/Engineering");
Object.defineProperty(exports, "Engineering", { enumerable: true, get: function () { return Engineering_1.Engineering; } });
var Explosives_1 = require("@civ-clone/base-science-advance-explosives/Explosives");
Object.defineProperty(exports, "Explosives", { enumerable: true, get: function () { return Explosives_1.Explosives; } });
var Feudalism_1 = require("@civ-clone/base-science-advance-feudalism/Feudalism");
Object.defineProperty(exports, "Feudalism", { enumerable: true, get: function () { return Feudalism_1.Feudalism; } });
var Flight_1 = require("@civ-clone/base-science-advance-flight/Flight");
Object.defineProperty(exports, "Flight", { enumerable: true, get: function () { return Flight_1.Flight; } });
var FusionPower_1 = require("@civ-clone/base-science-advance-fusionpower/FusionPower");
Object.defineProperty(exports, "FusionPower", { enumerable: true, get: function () { return FusionPower_1.FusionPower; } });
var GeneticEngineering_1 = require("@civ-clone/base-science-advance-geneticengineering/GeneticEngineering");
Object.defineProperty(exports, "GeneticEngineering", { enumerable: true, get: function () { return GeneticEngineering_1.GeneticEngineering; } });
var Gunpowder_1 = require("@civ-clone/base-science-advance-gunpowder/Gunpowder");
Object.defineProperty(exports, "Gunpowder", { enumerable: true, get: function () { return Gunpowder_1.Gunpowder; } });
var HorsebackRiding_1 = require("@civ-clone/base-science-advance-horsebackriding/HorsebackRiding");
Object.defineProperty(exports, "HorsebackRiding", { enumerable: true, get: function () { return HorsebackRiding_1.HorsebackRiding; } });
var Industrialization_1 = require("@civ-clone/base-science-advance-industrialization/Industrialization");
Object.defineProperty(exports, "Industrialization", { enumerable: true, get: function () { return Industrialization_1.Industrialization; } });
var Invention_1 = require("@civ-clone/base-science-advance-invention/Invention");
Object.defineProperty(exports, "Invention", { enumerable: true, get: function () { return Invention_1.Invention; } });
var IronWorking_1 = require("@civ-clone/base-science-advance-ironworking/IronWorking");
Object.defineProperty(exports, "IronWorking", { enumerable: true, get: function () { return IronWorking_1.IronWorking; } });
var LaborUnion_1 = require("@civ-clone/base-science-advance-laborunion/LaborUnion");
Object.defineProperty(exports, "LaborUnion", { enumerable: true, get: function () { return LaborUnion_1.LaborUnion; } });
var Literacy_1 = require("@civ-clone/base-science-advance-literacy/Literacy");
Object.defineProperty(exports, "Literacy", { enumerable: true, get: function () { return Literacy_1.Literacy; } });
var Magnetism_1 = require("@civ-clone/base-science-advance-magnetism/Magnetism");
Object.defineProperty(exports, "Magnetism", { enumerable: true, get: function () { return Magnetism_1.Magnetism; } });
var MapMaking_1 = require("@civ-clone/base-science-advance-mapmaking/MapMaking");
Object.defineProperty(exports, "MapMaking", { enumerable: true, get: function () { return MapMaking_1.MapMaking; } });
var Masonry_1 = require("@civ-clone/base-science-advance-masonry/Masonry");
Object.defineProperty(exports, "Masonry", { enumerable: true, get: function () { return Masonry_1.Masonry; } });
var MassProduction_1 = require("@civ-clone/base-science-advance-massproduction/MassProduction");
Object.defineProperty(exports, "MassProduction", { enumerable: true, get: function () { return MassProduction_1.MassProduction; } });
var Mathematics_1 = require("@civ-clone/base-science-advance-mathematics/Mathematics");
Object.defineProperty(exports, "Mathematics", { enumerable: true, get: function () { return Mathematics_1.Mathematics; } });
var Medicine_1 = require("@civ-clone/base-science-advance-medicine/Medicine");
Object.defineProperty(exports, "Medicine", { enumerable: true, get: function () { return Medicine_1.Medicine; } });
var Metallurgy_1 = require("@civ-clone/base-science-advance-metallurgy/Metallurgy");
Object.defineProperty(exports, "Metallurgy", { enumerable: true, get: function () { return Metallurgy_1.Metallurgy; } });
var Monarchy_1 = require("@civ-clone/base-science-advance-monarchy/Monarchy");
Object.defineProperty(exports, "Monarchy", { enumerable: true, get: function () { return Monarchy_1.Monarchy; } });
var Mysticism_1 = require("@civ-clone/base-science-advance-mysticism/Mysticism");
Object.defineProperty(exports, "Mysticism", { enumerable: true, get: function () { return Mysticism_1.Mysticism; } });
var Navigation_1 = require("@civ-clone/base-science-advance-navigation/Navigation");
Object.defineProperty(exports, "Navigation", { enumerable: true, get: function () { return Navigation_1.Navigation; } });
var NuclearFission_1 = require("@civ-clone/base-science-advance-nuclearfission/NuclearFission");
Object.defineProperty(exports, "NuclearFission", { enumerable: true, get: function () { return NuclearFission_1.NuclearFission; } });
var NuclearPower_1 = require("@civ-clone/base-science-advance-nuclearpower/NuclearPower");
Object.defineProperty(exports, "NuclearPower", { enumerable: true, get: function () { return NuclearPower_1.NuclearPower; } });
var Philosophy_1 = require("@civ-clone/base-science-advance-philosophy/Philosophy");
Object.defineProperty(exports, "Philosophy", { enumerable: true, get: function () { return Philosophy_1.Philosophy; } });
var Physics_1 = require("@civ-clone/base-science-advance-physics/Physics");
Object.defineProperty(exports, "Physics", { enumerable: true, get: function () { return Physics_1.Physics; } });
var Plastics_1 = require("@civ-clone/base-science-advance-plastics/Plastics");
Object.defineProperty(exports, "Plastics", { enumerable: true, get: function () { return Plastics_1.Plastics; } });
var Pottery_1 = require("@civ-clone/base-science-advance-pottery/Pottery");
Object.defineProperty(exports, "Pottery", { enumerable: true, get: function () { return Pottery_1.Pottery; } });
var Railroad_1 = require("@civ-clone/base-science-advance-railroad/Railroad");
Object.defineProperty(exports, "Railroad", { enumerable: true, get: function () { return Railroad_1.Railroad; } });
var Recycling_1 = require("@civ-clone/base-science-advance-recycling/Recycling");
Object.defineProperty(exports, "Recycling", { enumerable: true, get: function () { return Recycling_1.Recycling; } });
var Refining_1 = require("@civ-clone/base-science-advance-refining/Refining");
Object.defineProperty(exports, "Refining", { enumerable: true, get: function () { return Refining_1.Refining; } });
var Religion_1 = require("@civ-clone/base-science-advance-religion/Religion");
Object.defineProperty(exports, "Religion", { enumerable: true, get: function () { return Religion_1.Religion; } });
var Robotics_1 = require("@civ-clone/base-science-advance-robotics/Robotics");
Object.defineProperty(exports, "Robotics", { enumerable: true, get: function () { return Robotics_1.Robotics; } });
var Rocketry_1 = require("@civ-clone/base-science-advance-rocketry/Rocketry");
Object.defineProperty(exports, "Rocketry", { enumerable: true, get: function () { return Rocketry_1.Rocketry; } });
var SpaceFlight_1 = require("@civ-clone/base-science-advance-spaceflight/SpaceFlight");
Object.defineProperty(exports, "SpaceFlight", { enumerable: true, get: function () { return SpaceFlight_1.SpaceFlight; } });
var SteamEngine_1 = require("@civ-clone/base-science-advance-steamengine/SteamEngine");
Object.defineProperty(exports, "SteamEngine", { enumerable: true, get: function () { return SteamEngine_1.SteamEngine; } });
var Steel_1 = require("@civ-clone/base-science-advance-steel/Steel");
Object.defineProperty(exports, "Steel", { enumerable: true, get: function () { return Steel_1.Steel; } });
var Superconductor_1 = require("@civ-clone/base-science-advance-superconductor/Superconductor");
Object.defineProperty(exports, "Superconductor", { enumerable: true, get: function () { return Superconductor_1.Superconductor; } });
var TheRepublic_1 = require("@civ-clone/base-science-advance-therepublic/TheRepublic");
Object.defineProperty(exports, "TheRepublic", { enumerable: true, get: function () { return TheRepublic_1.TheRepublic; } });
var TheWheel_1 = require("@civ-clone/base-science-advance-thewheel/TheWheel");
Object.defineProperty(exports, "TheWheel", { enumerable: true, get: function () { return TheWheel_1.TheWheel; } });
var TheoryOfGravity_1 = require("@civ-clone/base-science-advance-theoryofgravity/TheoryOfGravity");
Object.defineProperty(exports, "TheoryOfGravity", { enumerable: true, get: function () { return TheoryOfGravity_1.TheoryOfGravity; } });
var Trade_1 = require("@civ-clone/base-science-advance-trade/Trade");
Object.defineProperty(exports, "Trade", { enumerable: true, get: function () { return Trade_1.Trade; } });
var University_1 = require("@civ-clone/base-science-advance-university/University");
Object.defineProperty(exports, "University", { enumerable: true, get: function () { return University_1.University; } });
var Writing_1 = require("@civ-clone/base-science-advance-writing/Writing");
Object.defineProperty(exports, "Writing", { enumerable: true, get: function () { return Writing_1.Writing; } });
//# sourceMappingURL=Advances.js.map