"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Writing = exports.TheWheel = exports.TheRepublic = exports.Pottery = exports.Navigation = exports.Mysticism = exports.Monarchy = exports.Mathematics = exports.Masonry = exports.MapMaking = exports.Literacy = exports.IronWorking = exports.Invention = exports.HorsebackRiding = exports.Gunpowder = exports.Feudalism = exports.Engineering = exports.Currency = exports.Construction = exports.CodeOfLaws = exports.Chivalry = exports.CeremonialBurial = exports.BronzeWorking = exports.BridgeBuilding = exports.Astronomy = exports.Alphabet = void 0;
var Alphabet_1 = require("@civ-clone/base-science-advance-alphabet/Alphabet");
Object.defineProperty(exports, "Alphabet", { enumerable: true, get: function () { return Alphabet_1.Alphabet; } });
var Astronomy_1 = require("@civ-clone/base-science-advance-astronomy/Astronomy");
Object.defineProperty(exports, "Astronomy", { enumerable: true, get: function () { return Astronomy_1.Astronomy; } });
var BridgeBuilding_1 = require("@civ-clone/base-science-advance-bridgebuilding/BridgeBuilding");
Object.defineProperty(exports, "BridgeBuilding", { enumerable: true, get: function () { return BridgeBuilding_1.BridgeBuilding; } });
var BronzeWorking_1 = require("@civ-clone/base-science-advance-bronzeworking/BronzeWorking");
Object.defineProperty(exports, "BronzeWorking", { enumerable: true, get: function () { return BronzeWorking_1.BronzeWorking; } });
var CeremonialBurial_1 = require("@civ-clone/base-science-advance-ceremonialburial/CeremonialBurial");
Object.defineProperty(exports, "CeremonialBurial", { enumerable: true, get: function () { return CeremonialBurial_1.CeremonialBurial; } });
var Chivalry_1 = require("@civ-clone/base-science-advance-chivalry/Chivalry");
Object.defineProperty(exports, "Chivalry", { enumerable: true, get: function () { return Chivalry_1.Chivalry; } });
var CodeOfLaws_1 = require("@civ-clone/base-science-advance-codeoflaws/CodeOfLaws");
Object.defineProperty(exports, "CodeOfLaws", { enumerable: true, get: function () { return CodeOfLaws_1.CodeOfLaws; } });
var Construction_1 = require("@civ-clone/base-science-advance-construction/Construction");
Object.defineProperty(exports, "Construction", { enumerable: true, get: function () { return Construction_1.Construction; } });
var Currency_1 = require("@civ-clone/base-science-advance-currency/Currency");
Object.defineProperty(exports, "Currency", { enumerable: true, get: function () { return Currency_1.Currency; } });
var Engineering_1 = require("@civ-clone/base-science-advance-engineering/Engineering");
Object.defineProperty(exports, "Engineering", { enumerable: true, get: function () { return Engineering_1.Engineering; } });
var Feudalism_1 = require("@civ-clone/base-science-advance-feudalism/Feudalism");
Object.defineProperty(exports, "Feudalism", { enumerable: true, get: function () { return Feudalism_1.Feudalism; } });
var Gunpowder_1 = require("@civ-clone/base-science-advance-gunpowder/Gunpowder");
Object.defineProperty(exports, "Gunpowder", { enumerable: true, get: function () { return Gunpowder_1.Gunpowder; } });
var HorsebackRiding_1 = require("@civ-clone/base-science-advance-horsebackriding/HorsebackRiding");
Object.defineProperty(exports, "HorsebackRiding", { enumerable: true, get: function () { return HorsebackRiding_1.HorsebackRiding; } });
var Invention_1 = require("@civ-clone/base-science-advance-invention/Invention");
Object.defineProperty(exports, "Invention", { enumerable: true, get: function () { return Invention_1.Invention; } });
var IronWorking_1 = require("@civ-clone/base-science-advance-ironworking/IronWorking");
Object.defineProperty(exports, "IronWorking", { enumerable: true, get: function () { return IronWorking_1.IronWorking; } });
var Literacy_1 = require("@civ-clone/base-science-advance-literacy/Literacy");
Object.defineProperty(exports, "Literacy", { enumerable: true, get: function () { return Literacy_1.Literacy; } });
var MapMaking_1 = require("@civ-clone/base-science-advance-mapmaking/MapMaking");
Object.defineProperty(exports, "MapMaking", { enumerable: true, get: function () { return MapMaking_1.MapMaking; } });
var Masonry_1 = require("@civ-clone/base-science-advance-masonry/Masonry");
Object.defineProperty(exports, "Masonry", { enumerable: true, get: function () { return Masonry_1.Masonry; } });
var Mathematics_1 = require("@civ-clone/base-science-advance-mathematics/Mathematics");
Object.defineProperty(exports, "Mathematics", { enumerable: true, get: function () { return Mathematics_1.Mathematics; } });
var Monarchy_1 = require("@civ-clone/base-science-advance-monarchy/Monarchy");
Object.defineProperty(exports, "Monarchy", { enumerable: true, get: function () { return Monarchy_1.Monarchy; } });
var Mysticism_1 = require("@civ-clone/base-science-advance-mysticism/Mysticism");
Object.defineProperty(exports, "Mysticism", { enumerable: true, get: function () { return Mysticism_1.Mysticism; } });
var Navigation_1 = require("@civ-clone/base-science-advance-navigation/Navigation");
Object.defineProperty(exports, "Navigation", { enumerable: true, get: function () { return Navigation_1.Navigation; } });
var Pottery_1 = require("@civ-clone/base-science-advance-pottery/Pottery");
Object.defineProperty(exports, "Pottery", { enumerable: true, get: function () { return Pottery_1.Pottery; } });
var TheRepublic_1 = require("@civ-clone/base-science-advance-therepublic/TheRepublic");
Object.defineProperty(exports, "TheRepublic", { enumerable: true, get: function () { return TheRepublic_1.TheRepublic; } });
var TheWheel_1 = require("@civ-clone/base-science-advance-thewheel/TheWheel");
Object.defineProperty(exports, "TheWheel", { enumerable: true, get: function () { return TheWheel_1.TheWheel; } });
var Writing_1 = require("@civ-clone/base-science-advance-writing/Writing");
Object.defineProperty(exports, "Writing", { enumerable: true, get: function () { return Writing_1.Writing; } });
//# sourceMappingURL=Advances.js.map